### ISSUE TITLE
highlight as background?

### ISSUE THREAD

**Issue by sebfindling** [akonwi/git-plus#526]
Hello, i'm wondering if it would be possible to have diff highlight showed as text background instead of underline, like all other git clients out there, since it's easier to read?

cheers

**Comment by rumpelsepp** [comment]
I wanted to open the exact same issue right now!

**Comment by sharedprophet** [comment]
See my answer on #523.

**Comment by sebfindling** [comment]
@sharedprophet i see you can now disable diff, but we _do_ want diff coloring, just as background instead as underline, do you think this could be possible?

**Comment by sharedprophet** [comment]
@sebfindling I explained how to do that in my answer on #523. With Atom 1.13.1 they changed the css to use "syntax--" as a prefix for all syntax css classes, so now it would be something like:

```less
atom-text-editor {
  .syntax--markup.syntax--removed.syntax--diff {
    border-bottom: none!important;
    background-color: @syntax-color-removed;
  }
  .syntax--markup.syntax--added.syntax--diff {
    border-bottom: none!important;
    background-color: @syntax-color-added;
  }
}
```
